"""Added uuid

Revision ID: fe205504289e
Revises: c20dcfb8069b
Create Date: 2023-12-07 16:32:36.987812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe205504289e'
down_revision: Union[str, None] = 'c20dcfb8069b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Graphic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('hour', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='google_trends'
    )
    op.create_index(op.f('ix_google_trends_Graphic_id'), 'Graphic', ['id'], unique=False, schema='google_trends')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
